<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Spandana-PC" failures="2" tests="2" name="Test(failed)" time="0.075" errors="0" timestamp="21 Dec 2018 13:47:51 GMT">
  <testcase classname="test.practice.Test_Failed_Test" name="test4" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.practice.Test_Failed_Test.test4(Test_Failed_Test.java:29)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="test.practice.Test_Failed_Test" name="test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.practice.Test_Failed_Test.test2(Test_Failed_Test.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="test.practice.Test_Failed_Test" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="test.practice.Test_Failed_Test" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test(failed) -->
